env:
  browser: true
  es2021: true
  jest: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes: warn
  semi: warn
  space-before-function-paren: warn
