env:
  browser: true
  es2021: true
plugins: [snakecase]
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  snakecase/snakecase: "error"
  quotes: warn
  semi: warn
  space-before-function-paren: warn
  camelcase: off
